languageCode = "en-AU"
languageName = "English (Australia)"
languageDirection = "ltr"
weight = 1

title = "Congo"
copyright = "&copy; 2023 Congo contributors"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "Fatih Kansoy personal website"

[params.author]
  name = "Congo"
  image = "img/author.jpg"
  headline = ""
  bio = "This is an example author bio, and although there's a stock photo of a dog here, this article was actually created by a human. :dog:"
  links = [
    { x-twitter = "https://twitter.com/kansoy" },
    { facebook = "https://facebook.com/kansoy" },
    { linkedin = "https://linkedin.com/in/kansoy" },
    { youtube = "https://youtube.com/fatihkanoy" },
  ]